import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useRef,
  useState,
  type ReactNode,
} from "react";
import {
  cropPages as apiCropPages,
  deletePages as apiDeletePages,
  duplicatePages as apiDuplicatePages,
  extractPages as apiExtractPages,
  getWorkingPages,
  insertBlankPage,
  insertUploadedPage,
  mergeDocument as apiMergeDocument,
  redoOperation,
  replacePage as apiReplacePage,
  reorderPages as apiReorderPages,
  rotatePages as apiRotatePages,
  saveDocument,
  saveDocumentAs,
  splitDocument as apiSplitDocument,
  undoOperation,
  documentThumbnailUrl,
  workingThumbnailUrl,
  type CropBox,
  type NewDocumentRef,
  type WorkingPageMeta,
} from "../lib/api";
import { extractErrorMessage } from "../lib/errors";
import { useOpenDocument } from "./useOpenDocument";

const POLL_INTERVAL_MS = 900;
const POLL_MAX_ATTEMPTS = 60; // ~54s ceiling — matches Phase 2's tolerance for a slow job.
const NOTICE_TIMEOUT_MS = 5000;

export interface NoticeAction {
  label: string;
  onClick: () => void;
}

export interface Notice {
  type: "success" | "error";
  message: string;
  action?: NoticeAction;
}

interface WorkingDocumentContextValue {
  pages: WorkingPageMeta[];
  pageCount: number;
  canUndo: boolean;
  canRedo: boolean;
  /** True while thumbnails/page metadata for the current working step are
   * still being generated by the backend's queued job — see
   * ARCHITECTURE.md's Phase 3 section on GenerateWorkingThumbnails. */
  thumbnailsPending: boolean;
  /** Bumped only when an operation genuinely mutates the working copy's
   * page structure (delete/reorder/duplicate/rotate/crop/insert/replace/
   * merge/undo/redo) — never on a routine thumbnail-poll tick. Consumed by
   * usePageSelection to drop a selection whose page numbers may no longer
   * mean the same thing (e.g. after a delete or reorder). */
  revision: number;
  /** True while any operation request is in flight — every ORGANIZE/Save/
   * Undo/Redo command gets disabled for the duration via this, so two
   * operations can never race the same working copy. */
  busy: boolean;
  busyLabel: string | null;
  notice: Notice | null;
  dismissNotice: () => void;
  /** Posts a notice through the same channel operations use — for a
   * purely informational message that isn't itself the result of an API
   * call (e.g. "drag pages to reorder"). */
  notify: (notice: Notice) => void;
  thumbnailUrl: (pageNumber: number) => string;

  runDelete: (pages: number[]) => Promise<void>;
  runDuplicate: (pages: number[]) => Promise<void>;
  runRotate: (pages: number[], degrees: 90 | 180 | 270 | -90) => Promise<void>;
  runReorder: (newOrder: number[]) => Promise<void>;
  runInsertBlank: (afterPage: number) => Promise<void>;
  runInsertUpload: (afterPage: number, file: File) => Promise<void>;
  runReplace: (page: number, file: File, replacementPage?: number) => Promise<void>;
  runCrop: (pages: number[], box: CropBox) => Promise<void>;
  runMerge: (withDocumentId: string, position: "before" | "after") => Promise<void>;
  runExtract: (pages: number[]) => Promise<void>;
  runSplit: (ranges: [number, number][]) => Promise<void>;
  undo: () => Promise<void>;
  redo: () => Promise<void>;
  save: () => Promise<void>;
  saveAs: (title: string) => Promise<void>;

  insertDialogOpen: boolean;
  openInsertDialog: () => void;
  closeInsertDialog: () => void;

  replaceDialogOpen: boolean;
  replaceTargetPage: number | null;
  openReplaceDialog: (page: number) => void;
  closeReplaceDialog: () => void;

  mergeDialogOpen: boolean;
  openMergeDialog: () => void;
  closeMergeDialog: () => void;

  splitDialogOpen: boolean;
  openSplitDialog: () => void;
  closeSplitDialog: () => void;

  saveAsDialogOpen: boolean;
  openSaveAsDialog: () => void;
  closeSaveAsDialog: () => void;

  cropDialogOpen: boolean;
  cropTargetPages: number[];
  openCropDialog: (pages: number[]) => void;
  closeCropDialog: () => void;
}

const WorkingDocumentContext = createContext<WorkingDocumentContextValue | null>(null);

/**
 * Owns Phase 3's real page-management state for whichever document
 * useOpenDocument currently has open: the working copy's real page list
 * (polled from GET .../working/pages, which itself falls back to the base
 * version's pages server-side when there are no pending edits — see
 * ARCHITECTURE.md), undo/redo pointers, and every ORGANIZE operation. Every
 * `run*` function below calls a real backend endpoint from lib/api.ts —
 * nothing here mutates a PDF client-side. Nested inside OpenDocumentProvider
 * because it needs the open document's id/status and (for Extract/Split/
 * Save As's "open the result" affordance) openExisting.
 */
export function WorkingDocumentProvider({ children }: { children: ReactNode }) {
  const { document: doc, openExisting } = useOpenDocument();

  const [pages, setPages] = useState<WorkingPageMeta[]>([]);
  const [pageCount, setPageCount] = useState(0);
  const [canUndo, setCanUndo] = useState(false);
  const [canRedo, setCanRedo] = useState(false);
  const [source, setSource] = useState<"step" | "version">("version");
  const [thumbnailsPending, setThumbnailsPending] = useState(false);
  const [busy, setBusy] = useState(false);
  const [busyLabel, setBusyLabel] = useState<string | null>(null);
  const [notice, setNotice] = useState<Notice | null>(null);
  const [revision, setRevision] = useState(0);

  const [insertDialogOpen, setInsertDialogOpen] = useState(false);
  const [replaceDialogOpen, setReplaceDialogOpen] = useState(false);
  const [replaceTargetPage, setReplaceTargetPage] = useState<number | null>(null);
  const [mergeDialogOpen, setMergeDialogOpen] = useState(false);
  const [splitDialogOpen, setSplitDialogOpen] = useState(false);
  const [saveAsDialogOpen, setSaveAsDialogOpen] = useState(false);
  const [cropDialogOpen, setCropDialogOpen] = useState(false);
  const [cropTargetPages, setCropTargetPages] = useState<number[]>([]);

  const pollGenerationRef = useRef(0);
  const pollTimeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const noticeTimeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  const dismissNotice = useCallback(() => {
    if (noticeTimeoutRef.current) clearTimeout(noticeTimeoutRef.current);
    setNotice(null);
  }, []);

  const showNotice = useCallback((next: Notice) => {
    if (noticeTimeoutRef.current) clearTimeout(noticeTimeoutRef.current);
    setNotice(next);
    noticeTimeoutRef.current = setTimeout(() => setNotice(null), NOTICE_TIMEOUT_MS);
  }, []);

  const stopPolling = useCallback(() => {
    if (pollTimeoutRef.current) {
      clearTimeout(pollTimeoutRef.current);
      pollTimeoutRef.current = null;
    }
    pollGenerationRef.current += 1;
  }, []);

  // Poll GET .../working/pages until the working step's thumbnail job
  // settles (`pending` false and every page reports thumbnailReady) — the
  // same "poll until settled" shape Phase 2's useOpenDocument already
  // established for the upload flow, applied here to the working copy.
  const pollWorkingPages = useCallback(
    (documentId: string, attempt = 0) => {
      stopPolling();
      const generation = pollGenerationRef.current;

      const tick = async (n: number) => {
        if (pollGenerationRef.current !== generation) return;
        try {
          const response = await getWorkingPages(documentId);
          if (pollGenerationRef.current !== generation) return;
          setPages(response.pages);
          setSource(response.source);
          const allReady =
            response.pages.length > 0 && response.pages.every((p) => p.thumbnailReady);
          const stillPending = response.pending || !allReady;
          setThumbnailsPending(stillPending);
          if (stillPending && n < POLL_MAX_ATTEMPTS) {
            pollTimeoutRef.current = setTimeout(() => void tick(n + 1), POLL_INTERVAL_MS);
          }
        } catch {
          if (pollGenerationRef.current === generation && n < POLL_MAX_ATTEMPTS) {
            pollTimeoutRef.current = setTimeout(() => void tick(n + 1), POLL_INTERVAL_MS);
          }
        }
      };

      void tick(attempt);
    },
    [stopPolling],
  );

  // Reset and (re)fetch whenever the open document changes identity or
  // finishes its own Phase 2 processing.
  useEffect(() => {
    stopPolling();
    setInsertDialogOpen(false);
    setReplaceDialogOpen(false);
    setMergeDialogOpen(false);
    setSplitDialogOpen(false);
    setSaveAsDialogOpen(false);
    setCropDialogOpen(false);
    dismissNotice();

    if (!doc || doc.status !== "ready") {
      setPages([]);
      setPageCount(0);
      setCanUndo(false);
      setCanRedo(false);
      setSource("version");
      setThumbnailsPending(false);
      return;
    }

    setPageCount(doc.pageCount ?? 0);
    (async () => {
      try {
        const response = await getWorkingPages(doc.id);
        // GET working/pages doesn't expose canRedo (only operation/undo/
        // redo responses do) — a pending edit found on load (source
        // "step") means canUndo is real, but redo history from a prior
        // session isn't knowable from this endpoint, so it starts false.
        // Documented limitation, not an oversight — see Phase 3 (frontend)
        // ARCHITECTURE.md notes.
        setCanUndo(response.source === "step");
        setCanRedo(false);
        setSource(response.source);
        setPages(response.pages);
        const allReady = response.pages.length > 0 && response.pages.every((p) => p.thumbnailReady);
        setThumbnailsPending(response.pending || !allReady);
        if (response.pending || !allReady) pollWorkingPages(doc.id);
      } catch {
        // Non-fatal — the thumbnail panel just shows fewer ready items.
      }
    })();

    return () => stopPolling();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [doc?.id, doc?.status]);

  useEffect(() => () => stopPolling(), [stopPolling]);
  useEffect(() => () => dismissNotice(), [dismissNotice]);

  const thumbnailUrl = useCallback(
    (pageNumber: number) => {
      if (!doc) return "";
      return source === "step"
        ? workingThumbnailUrl(doc.id, pageNumber)
        : documentThumbnailUrl(doc.id, pageNumber);
    },
    [doc, source],
  );

  /** Wraps every mutating call: sets busy/label, runs it, applies the
   * OperationResult to local state, kicks off thumbnail polling, and turns
   * any rejection into a real, specific notice — never a silent failure. */
  const runMutating = useCallback(
    async (label: string, action: () => Promise<{ pageCount: number; canUndo: boolean; canRedo: boolean }>) => {
      if (!doc || busy) return;
      setBusy(true);
      setBusyLabel(label);
      try {
        const result = await action();
        setPageCount(result.pageCount);
        setCanUndo(result.canUndo);
        setCanRedo(result.canRedo);
        setSource("step");
        setThumbnailsPending(true);
        setRevision((r) => r + 1);
        pollWorkingPages(doc.id);
      } catch (error) {
        showNotice({ type: "error", message: extractErrorMessage(error, `${label} failed.`) });
      } finally {
        setBusy(false);
        setBusyLabel(null);
      }
    },
    [doc, busy, pollWorkingPages, showNotice],
  );

  const runDelete = useCallback(
    (targetPages: number[]) =>
      runMutating("Deleting page(s)…", () => {
        if (!doc) throw new Error("No document open");
        return apiDeletePages(doc.id, targetPages);
      }),
    [doc, runMutating],
  );

  const runDuplicate = useCallback(
    (targetPages: number[]) =>
      runMutating("Duplicating page(s)…", () => {
        if (!doc) throw new Error("No document open");
        return apiDuplicatePages(doc.id, targetPages);
      }),
    [doc, runMutating],
  );

  const runRotate = useCallback(
    (targetPages: number[], degrees: 90 | 180 | 270 | -90) =>
      runMutating("Rotating page(s)…", () => {
        if (!doc) throw new Error("No document open");
        return apiRotatePages(doc.id, targetPages, degrees);
      }),
    [doc, runMutating],
  );

  const runReorder = useCallback(
    (newOrder: number[]) =>
      runMutating("Reordering pages…", () => {
        if (!doc) throw new Error("No document open");
        return apiReorderPages(doc.id, newOrder);
      }),
    [doc, runMutating],
  );

  const runInsertBlank = useCallback(
    (afterPage: number) =>
      runMutating("Inserting page…", () => {
        if (!doc) throw new Error("No document open");
        return insertBlankPage(doc.id, afterPage);
      }),
    [doc, runMutating],
  );

  const runInsertUpload = useCallback(
    (afterPage: number, file: File) =>
      runMutating("Inserting page…", () => {
        if (!doc) throw new Error("No document open");
        return insertUploadedPage(doc.id, afterPage, file);
      }),
    [doc, runMutating],
  );

  const runReplace = useCallback(
    (page: number, file: File, replacementPage?: number) =>
      runMutating("Replacing page…", () => {
        if (!doc) throw new Error("No document open");
        return apiReplacePage(doc.id, page, file, replacementPage);
      }),
    [doc, runMutating],
  );

  const runCrop = useCallback(
    (targetPages: number[], box: CropBox) =>
      runMutating("Cropping page(s)…", () => {
        if (!doc) throw new Error("No document open");
        return apiCropPages(doc.id, targetPages, box);
      }),
    [doc, runMutating],
  );

  const runMerge = useCallback(
    (withDocumentId: string, position: "before" | "after") =>
      runMutating("Merging document…", () => {
        if (!doc) throw new Error("No document open");
        return apiMergeDocument(doc.id, withDocumentId, position);
      }),
    [doc, runMutating],
  );

  const openResultAction = useCallback(
    (ref: NewDocumentRef): NoticeAction => ({
      label: "Open",
      onClick: () => void openExisting(ref.id),
    }),
    [openExisting],
  );

  const runExtract = useCallback(
    async (targetPages: number[]) => {
      if (!doc || busy) return;
      setBusy(true);
      setBusyLabel("Extracting page(s)…");
      try {
        const ref = await apiExtractPages(doc.id, targetPages);
        showNotice({
          type: "success",
          message: `Extracted ${targetPages.length} page(s) into "${ref.title}".`,
          action: openResultAction(ref),
        });
      } catch (error) {
        showNotice({ type: "error", message: extractErrorMessage(error, "Extract failed.") });
      } finally {
        setBusy(false);
        setBusyLabel(null);
      }
    },
    [doc, busy, showNotice, openResultAction],
  );

  const runSplit = useCallback(
    async (ranges: [number, number][]) => {
      if (!doc || busy) return;
      setBusy(true);
      setBusyLabel("Splitting document…");
      try {
        const refs = await apiSplitDocument(doc.id, ranges);
        showNotice({
          type: "success",
          message: `Split into ${refs.length} new document(s).`,
          action: refs[0] ? openResultAction(refs[0]) : undefined,
        });
      } catch (error) {
        showNotice({ type: "error", message: extractErrorMessage(error, "Split failed.") });
      } finally {
        setBusy(false);
        setBusyLabel(null);
      }
    },
    [doc, busy, showNotice, openResultAction],
  );

  const undo = useCallback(async () => {
    if (!doc || busy || !canUndo) return;
    setBusy(true);
    setBusyLabel("Undoing…");
    try {
      const result = await undoOperation(doc.id);
      setPageCount(result.pageCount);
      setCanUndo(result.canUndo);
      setCanRedo(result.canRedo);
      setSource(result.currentStepId === null ? "version" : "step");
      setThumbnailsPending(true);
      setRevision((r) => r + 1);
      pollWorkingPages(doc.id);
    } catch (error) {
      showNotice({ type: "error", message: extractErrorMessage(error, "Undo failed.") });
    } finally {
      setBusy(false);
      setBusyLabel(null);
    }
  }, [doc, busy, canUndo, pollWorkingPages, showNotice]);

  const redo = useCallback(async () => {
    if (!doc || busy || !canRedo) return;
    setBusy(true);
    setBusyLabel("Redoing…");
    try {
      const result = await redoOperation(doc.id);
      setPageCount(result.pageCount);
      setCanUndo(result.canUndo);
      setCanRedo(result.canRedo);
      setSource(result.currentStepId === null ? "version" : "step");
      setThumbnailsPending(true);
      setRevision((r) => r + 1);
      pollWorkingPages(doc.id);
    } catch (error) {
      showNotice({ type: "error", message: extractErrorMessage(error, "Redo failed.") });
    } finally {
      setBusy(false);
      setBusyLabel(null);
    }
  }, [doc, busy, canRedo, pollWorkingPages, showNotice]);

  const save = useCallback(async () => {
    if (!doc || busy) return;
    if (!canUndo) {
      showNotice({ type: "success", message: "There are no pending changes to save." });
      return;
    }
    setBusy(true);
    setBusyLabel("Saving…");
    try {
      const result = await saveDocument(doc.id);
      setCanUndo(false);
      setCanRedo(false);
      setSource("version");
      showNotice({ type: "success", message: `Saved as version ${result.versionNumber}.` });
      pollWorkingPages(doc.id);
    } catch (error) {
      showNotice({ type: "error", message: extractErrorMessage(error, "Save failed.") });
    } finally {
      setBusy(false);
      setBusyLabel(null);
    }
  }, [doc, busy, canUndo, pollWorkingPages, showNotice]);

  const saveAs = useCallback(
    async (title: string) => {
      if (!doc || busy) return;
      setBusy(true);
      setBusyLabel("Saving a copy…");
      try {
        const ref = await saveDocumentAs(doc.id, title);
        setSaveAsDialogOpen(false);
        showNotice({
          type: "success",
          message: `Saved a copy as "${ref.title}".`,
          action: openResultAction(ref),
        });
      } catch (error) {
        showNotice({ type: "error", message: extractErrorMessage(error, "Save a Copy failed.") });
      } finally {
        setBusy(false);
        setBusyLabel(null);
      }
    },
    [doc, busy, showNotice, openResultAction],
  );

  const value: WorkingDocumentContextValue = {
    pages,
    pageCount,
    canUndo,
    canRedo,
    thumbnailsPending,
    revision,
    busy,
    busyLabel,
    notice,
    dismissNotice,
    notify: showNotice,
    thumbnailUrl,
    runDelete,
    runDuplicate,
    runRotate,
    runReorder,
    runInsertBlank,
    runInsertUpload,
    runReplace,
    runCrop,
    runMerge,
    runExtract,
    runSplit,
    undo,
    redo,
    save,
    saveAs,
    insertDialogOpen,
    openInsertDialog: () => setInsertDialogOpen(true),
    closeInsertDialog: () => setInsertDialogOpen(false),
    replaceDialogOpen,
    replaceTargetPage,
    openReplaceDialog: (page: number) => {
      setReplaceTargetPage(page);
      setReplaceDialogOpen(true);
    },
    closeReplaceDialog: () => setReplaceDialogOpen(false),
    mergeDialogOpen,
    openMergeDialog: () => setMergeDialogOpen(true),
    closeMergeDialog: () => setMergeDialogOpen(false),
    splitDialogOpen,
    openSplitDialog: () => setSplitDialogOpen(true),
    closeSplitDialog: () => setSplitDialogOpen(false),
    saveAsDialogOpen,
    openSaveAsDialog: () => setSaveAsDialogOpen(true),
    closeSaveAsDialog: () => setSaveAsDialogOpen(false),
    cropDialogOpen,
    cropTargetPages,
    openCropDialog: (targetPages: number[]) => {
      setCropTargetPages(targetPages);
      setCropDialogOpen(true);
    },
    closeCropDialog: () => setCropDialogOpen(false),
  };

  return <WorkingDocumentContext.Provider value={value}>{children}</WorkingDocumentContext.Provider>;
}

export function useWorkingDocument(): WorkingDocumentContextValue {
  const ctx = useContext(WorkingDocumentContext);
  if (!ctx) {
    throw new Error("useWorkingDocument must be used within a WorkingDocumentProvider");
  }
  return ctx;
}
